defmodule :"Elixir.Expensy.Repo.Migrations.Full-resourcesWith" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:expenses, "expenses_category_id_fkey")

    alter table(:expenses) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "expenses_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:expenses, [:category_id])

    alter table(:categories) do
      modify :monthly_budget, :money_with_currency, null: true
    end
  end

  def down do
    alter table(:categories) do
      modify :monthly_budget, :money_with_currency, null: false
    end

    drop_if_exists index(:expenses, [:category_id])

    drop constraint(:expenses, "expenses_category_id_fkey")

    alter table(:expenses) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "expenses_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
