defmodule Expensy.Repo.Migrations.Latest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:expenses) do
      modify :notes, :text, default: ""
    end
  end

  def down do
    alter table(:expenses) do
      modify :notes, :text, default: nil
    end
  end
end
